

---
engine: terraform
input:
  - OS_USERNAME
  - OS_PASSWORD
  - OS_AUTH_URL
  - OS_PROJECT_NAME
output:

  - instance_server_public_key_ubuntu_nginx_vm
  - instance_server_private_key_ubuntu_nginx_vm
  - instance_server_public_ip_nginx_vm

...
