pma_deployment_id: "{{ lookup('env', 'DEPLOYMENT_ID' ) }}" 
pma_influxdb_bucket:  "{{ lookup('env', 'INFLUXDB_BUCKET' ) }}"
pma_influxdb_token:  "{{ lookup('env', 'INFLUXDB_TOKEN' ) }}"
pma_influxdb_org:  "{{ lookup('env', 'INFLUXDB_ORG' ) }}"
pma_influxdb_addr:  "{{ lookup('env', 'INFLUXDB_ADDR' ) }}"

telegraf_agent_package_state: latest

telegraf_agent_output:
  - type: influxdb_v2
    config:
      - urls = ["{{ pma_influxdb_addr }}"]
      - token = "{{ pma_influxdb_token }}"
      - organization = "{{ pma_influxdb_org }}"
      - bucket = "{{ pma_influxdb_bucket }}"
      - insecure_skip_verify = true

telegraf_global_tags:
  - tag_name: deployment_id
    tag_value: "{{ pma_deployment_id }}"
  - tag_name: doml_element_name
    tag_value: "{{ doml_element_name }}"
  - tag_name: doml_element_type
    tag_value: "{{ doml_element_type | default('vm') }}"

telegraf_plugins_default:
  - plugin: cpu
  - plugin: mem
  - plugin: processes
  - plugin: disk
  - plugin: net
  - plugin: system
